### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by darakeon** [agaldino/ai-stone#1]
- [x] Api de alteração de dados
- [x] Integração com "jsonator"
- [x] Configuração do "jsonator"
- [ ] Revisar sinônimos, palavras-chaves
- [ ] Acessibilidade: ícones onde cores representam estados
- [x] Versionar configuração
- [x] App mobile
- [x] Interface web
